name: Get geocoding for specified locations
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: make install
    - name: Run geocoding script
      run: python geocoding.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
    - name: Commit changes to main branch
      run: |      
        git config --global user.email "geocoding42@gmail.com"
        git config --global user.name "Geoencoder"
        now=$(date)
        git add .
        git commit -m "Geoencoding changes as of '$now'"
        git push origin main
